-- CreateTable
CREATE TABLE "Provider" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "providerType" TEXT NOT NULL,
    "businessName" TEXT NOT NULL,
    "contactName" TEXT,
    "phone" TEXT,
    "email" TEXT,
    "instagram" TEXT,
    "website" TEXT,
    "zone" TEXT,
    "servicesOffered" TEXT,
    "minPrice" REAL,
    "avgPrice" REAL,
    "maxPrice" REAL,
    "specialConditions" TEXT,
    "availableDays" TEXT,
    "usualHours" TEXT,
    "setupTime" TEXT,
    "teardownTime" TEXT,
    "technicalNeeds" TEXT,
    "firstContactDate" DATETIME,
    "contactChannel" TEXT,
    "initialResponse" TEXT,
    "hired" BOOLEAN NOT NULL DEFAULT false,
    "relationshipType" TEXT,
    "agreedConditions" TEXT,
    "professionalism" INTEGER,
    "communication" INTEGER,
    "punctuality" INTEGER,
    "serviceQuality" INTEGER,
    "flexibility" INTEGER,
    "valueForMoney" INTEGER,
    "globalRating" INTEGER,
    "importantNotes" TEXT,
    "followUp" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);

-- CreateTable
CREATE TABLE "Client" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "fullName" TEXT NOT NULL,
    "phone" TEXT,
    "email" TEXT,
    "eventType" TEXT,
    "eventDate" DATETIME,
    "eventLocation" TEXT,
    "guestCount" INTEGER,
    "budgetMin" REAL,
    "budgetMax" REAL,
    "status" TEXT NOT NULL DEFAULT 'Lead',
    "source" TEXT,
    "assignedProviderType" TEXT,
    "notes" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);
